Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5

  Include:
    - "**/Rakefile"
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "bin/**/*"
    - "script/**/*"

inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
    - it
    - specify
Style/AndOr:
  EnforcedStyle: conditionals
Layout/CaseIndentation:
  IndentOneStep: true
Style/Documentation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/NumericLiterals:
  Enabled: true
  Exclude:
    - "spec/**/*"
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_special
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_special
Style/SingleLineBlockParams:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Layout/MultilineMethodCallIndentation:
  Exclude:
    - "spec/**/*.rb"
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/SymbolArray:
  MinSize: 4
Style/WordArray:
  MinSize: 4
Lint/UnusedBlockArgument:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Performance/Casecmp:
  Enabled: false
Performance/RedundantMerge:
  MaxKeyValuePairs: 1
Style/ClassCheck:
  Enabled: false
Style/SignalException:
  Enabled: false

