language: ruby
rvm:
  - "2.5"
  - "2.6"
  - "2.7"
before_install: gem update --system && gem install bundler
gemfile:
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
matrix:
  fast_finish: true
notifications:
  email: false
